<?php

session_start();

//IMPOSTARE NEL FILE PHP.ini:
// session.use_strict_mode=1 non fa creare un ID SESSIONE CON DATI ERRATI ATTRAVERSO JS INJECT O ATTRAVERSO LA CREAZIONE DI COOKIE,
// QUINDI GARANTISCE CHE TUTTE LE SEZIONI SONO AUTENTICHE

 ?>
